name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04 # Version stable de Linux sur GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-setuptools libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          # On ajoute le chemin de buildozer au système
          export PATH=$PATH:$HOME/.local/bin
          # On lance la compilation (cela va prendre 15-20 min)
          buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
