name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Version à jour

      - name: Build with Buildozer
        uses: EnisSari/buildozer-action@v2 # Un builder plus récent et fonctionnel
        with:
          buildozer_version: master
          python_version: 3.11

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Version 4 obligatoire en 2026
        with:
          name: package
          path: bin/*.apk
